export const DATA_TYPES = {
  CREATE_ROOM: 'createRoom',
  JOIN_ROOM: 'joinRoom',
  REMOVE_PLAYER: 'removePlayer',
  LEAVE_ROOM: 'leaveRoom',
  START_GAME: 'startGame',
  CHAT: 'chat',
  DRAW: 'draw',
  SYSTEM: 'system',
  ROOM_CREATED: 'roomCreated',
  PLAYER_REMOVED: 'playerRemoved',
  ROOM_JOINED: 'roomJoined',
  ROOM_LEFT: 'roomLeft',
  ROOM_LIST_UPDATE: 'roomListUpdate',
  ROOM_UPDATE: 'roomUpdate',
};
